### ISSUE TITLE
How do I choose the starting block?

### ISSUE THREAD

**Issue by RSNFreud** [1280px/hueblocks-legacy#1]
I want to choose the starting block but I'm not sure what colour it is

**Comment by 1280px** [comment]
For now, there's no way to do so. The only thing I can suggest is to open "[blocks.js](https://1280px.github.io/hueblocks/data/blocks.js)" (or "[blocks_pa.js](https://1280px.github.io/hueblocks/data/blocks_pa.js)" for Programmer's Art), find the block you want to start with, copy its RGB and type it in the color selector

Actually sounds like a pretty interesting suggestion to be added, though I'm not sure how to make it work :|

**Comment by 1280px** [comment]
### Added in the recent update
Hover the left/right part of the bar and click the block icon to open a block colour picker screen.
